// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeC7AjmgBGNippFaMK3ArUYjA0zHcKMQ4',
    appId: '1:150600351745:web:8f6b13a4f31f0b35f90000',
    messagingSenderId: '150600351745',
    projectId: 'flutter-social-login-2e09c',
    authDomain: 'flutter-social-login-2e09c.firebaseapp.com',
    storageBucket: 'flutter-social-login-2e09c.appspot.com',
    measurementId: 'G-7BMQJCH0NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXP5JFXUcA5hx74rf5A5Uk9Q9A_0J8Rq8',
    appId: '1:150600351745:android:7823069b089830cef90000',
    messagingSenderId: '150600351745',
    projectId: 'flutter-social-login-2e09c',
    storageBucket: 'flutter-social-login-2e09c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy6We0erncpxRQ7tG4JDkIepjSfylsUO0',
    appId: '1:150600351745:ios:3962fea64103e95cf90000',
    messagingSenderId: '150600351745',
    projectId: 'flutter-social-login-2e09c',
    storageBucket: 'flutter-social-login-2e09c.appspot.com',
    iosBundleId: 'com.example.flutterSocialLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy6We0erncpxRQ7tG4JDkIepjSfylsUO0',
    appId: '1:150600351745:ios:3962fea64103e95cf90000',
    messagingSenderId: '150600351745',
    projectId: 'flutter-social-login-2e09c',
    storageBucket: 'flutter-social-login-2e09c.appspot.com',
    iosBundleId: 'com.example.flutterSocialLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeC7AjmgBGNippFaMK3ArUYjA0zHcKMQ4',
    appId: '1:150600351745:web:fc02fa1c5d6bc705f90000',
    messagingSenderId: '150600351745',
    projectId: 'flutter-social-login-2e09c',
    authDomain: 'flutter-social-login-2e09c.firebaseapp.com',
    storageBucket: 'flutter-social-login-2e09c.appspot.com',
    measurementId: 'G-9E808XH0XF',
  );

}